config/routes.rb
Findagrapher::Application.routes.draw do
  resources :shoots

  resources :services

  resources :offerings

  resources :photographers, :login

  match 'photographers/:id/photos' => 'photographers#photos', :as => :photographers_photos
  match 'photographers/get_flickr_photo/:fid' => 'photographers#get_flickr_photo', :as => :get_flickr_photo

  root :to => 'home#index'

end

app/models/shoot.rb
class Shoot < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/shoots_controller.rb
class ShootsController < ApplicationController
  before_filter :authorize, :only => [:new]

  # GET /shoots
  # GET /shoots.json
  def index
    @shoots = Shoot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shoots }
    end
  end

  # GET /shoots/1
  # GET /shoots/1.json
  def show
    @shoot = Shoot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shoot }
    end
  end

  # GET /shoots/new
  # GET /shoots/new.json
  def new
    @shoot = Shoot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shoot }
    end
  end

  # GET /shoots/1/edit
  def edit
    @shoot = Shoot.find(params[:id])
  end

  # POST /shoots
  # POST /shoots.json
  def create
    @shoot = Shoot.new(params[:shoot])

    respond_to do |format|
      if @shoot.save
        format.html { redirect_to @shoot, notice: 'Shoot was successfully created.' }
        format.json { render json: @shoot, status: :created, location: @shoot }
      else
        format.html { render action: "new" }
        format.json { render json: @shoot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shoots/1
  # PUT /shoots/1.json
  def update
    @shoot = Shoot.find(params[:id])

    respond_to do |format|
      if @shoot.update_attributes(params[:shoot])
        format.html { redirect_to @shoot, notice: 'Shoot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shoot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoots/1
  # DELETE /shoots/1.json
  def destroy
    @shoot = Shoot.find(params[:id])
    @shoot.destroy

    respond_to do |format|
      format.html { redirect_to shoots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shoots_helper.rb
module ShootsHelper
end

app/views/shoots/_form.html.erb
<div class="form">
  <%= form_for(@shoot) do |f| %>
    <% if @shoot.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@shoot.errors.count, "error") %> prohibited this shoot from being saved:</h2>

        <ul>
        <% @shoot.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <h3 class="span8 offset4">Tell us what you need.</h3>
    </div>

    <div class="row">
      <div class="f-name span4">
        Name: (Demo field)
      </div>
      <div class="f-content span8">
        <%= f.text_field :name %>
      </div>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        I need a photographer for:
      </div>
      <div class="f-content span8">
        <%
          types = ['Wedding', 'Reception', 'Engagement', 'Pre/Post Wedding', 'New Born', 'Babies']
          types.each_with_index do |o|
        %>
          <div class="option">
            <input type="checkbox" />
            <%= o %>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        I'm looking for:
      </div>
      <div class="f-content span8">
        <%
          types = ['Creative Photography', 'Standard Photography', 'Creative Video']
          types.each_with_index do |o|
        %>
          <div class="option">
            <input type="checkbox" />
            <%= o %>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        After the shoot, I need:
      </div>
      <div class="f-content span8">
        <%
          types = ['Digital Photos', 'Album', 'Video', 'Small Prints', 'Big Prints']
          types.each_with_index do |o|
        %>
          <div class="option">
            <input type="checkbox" />
            <%= o %>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        My total budget is:
      </div>
      <div class="f-content span8">
        Rupees <input type="text" />
      </div>
    </div>

    <div class="row">
      <h3 class="span8 offset4">How would you like to be notified?</h3>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        E-Mail:
      </div>
      <div class="f-content span8">
        <input type="text" />
        <br/>
        <div class="note">
          <h4>We won't spam you.</h4>
          <div>
            Remember, you can always instantaly turn off this notification once you find your photographer.
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        Notify:
      </div>
      <div class="f-content span8">
        <%
          types = ['Once a day', 'Twice a week', 'Once a week']
          types.each_with_index do |o|
        %>
          <div class="option">
            <input type="checkbox" />
            <%= o %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="f-content span8 offset4">
        <%= f.submit "Place Request", :class => "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/shoots/edit.html.erb
<h1>Editing shoot</h1>

<%= render 'form' %>

<%= link_to 'Show', @shoot %> |
<%= link_to 'Back', shoots_path %>

app/views/shoots/index.html.erb
<h1>Listing shoots</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shoots.each do |shoot| %>
  <tr>
    <td><%= shoot.name %></td>
    <td><%= link_to 'Show', shoot %></td>
    <td><%= link_to 'Edit', edit_shoot_path(shoot) %></td>
    <td><%= link_to 'Destroy', shoot, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shoot', new_shoot_path %>

app/views/shoots/new.html.erb
<div class="container">
	<div class="row">
		<div class="span12">
			<div class="white-box pad-top">
				<div class="title">
					<h2>Find a photographer</h2>
				</div>
				<div class="content">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shoots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shoot.name %>
</p>


<%= link_to 'Edit', edit_shoot_path(@shoot) %> |
<%= link_to 'Back', shoots_path %>