config/routes.rb
Findagrapher::Application.routes.draw do
  resources :shoots

  resources :services

  resources :offerings

  resources :photographers, :login

  match 'photographers/:id/photos' => 'photographers#photos', :as => :photographers_photos
  match 'photographers/get_flickr_photo/:fid' => 'photographers#get_flickr_photo', :as => :get_flickr_photo

  root :to => 'home#index'

end

app/models/offering.rb
class Offering < ActiveRecord::Base
  attr_accessible :offering
  has_and_belongs_to_many :photographers
end

app/controllers/offerings_controller.rb
class OfferingsController < ApplicationController
  # GET /offerings
  # GET /offerings.json
  def index
    @offerings = Offering.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offerings }
    end
  end

  # GET /offerings/1
  # GET /offerings/1.json
  def show
    @offering = Offering.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offering }
    end
  end

  # GET /offerings/new
  # GET /offerings/new.json
  def new
    @offering = Offering.new()

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offering }
    end
  end

  # GET /offerings/1/edit
  def edit
    @offering = Offering.find(params[:id])
  end

  # POST /offerings
  # POST /offerings.json
  def create
    @offering = Offering.new(params[:offering])

    respond_to do |format|
      if @offering.save
        format.html { redirect_to @offering, notice: 'Offering was successfully created.' }
        format.json { render json: @offering, status: :created, location: @offering }
      else
        format.html { render action: "new" }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offerings/1
  # PUT /offerings/1.json
  def update
    @offering = Offering.find(params[:id])

    respond_to do |format|
      if @offering.update_attributes(params[:offering])
        format.html { redirect_to @offering, notice: 'Offering was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offerings/1
  # DELETE /offerings/1.json
  def destroy
    @offering = Offering.find(params[:id])
    @offering.destroy

    respond_to do |format|
      format.html { redirect_to offerings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offerings_helper.rb
module OfferingsHelper
end

app/views/offerings/_form.html.erb
<fieldset>
  <legend>Offerings</legend>
  <p>
    <label for="offering">Offering</label>
    <%= text_field :offering, :offering, :value => @offering.offering %>
  </p>
</fieldset>

app/views/offerings/edit.html.erb
<h1>Editing offering</h1>

<%= form_for(@offering) do |f| %>
    <% if @offering.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@offering.errors.count, "error") %> prohibited this offering from being saved:</h2>

        <ul>
        <% @offering.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

	<%= render :partial => 'form',  :locals => { :offering => @offering }  %>
	<fieldset>
    	<%= f.submit "Update" %>
		<%= link_to 'Show', @offering %> |
		<%= link_to 'Back', offerings_path %>
  	</fieldset>
<% end %>

app/views/offerings/index.html.erb
<h1>Listing offerings</h1>

<table>
  <tr>
    <th>Offering</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offerings.each do |offering| %>
  <tr>
    <td><%= offering.offering %></td>
    <td><%= link_to 'Show', offering %></td>
    <td><%= link_to 'Edit', edit_offering_path(offering) %></td>
    <td><%= link_to 'Destroy', offering, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Offering', new_offering_path %>

app/views/offerings/new.html.erb
<h1>New offering</h1>

<%= form_for(@offering) do |f| %>
    <% if @offering.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@offering.errors.count, "error") %> prohibited this offering from being saved:</h2>

        <ul>
        <% @offering.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
	
	<%= render :partial => 'form',  :locals => { :offering => @offering }  %>
  	<fieldset>
    	<%= f.submit "Create" %>
		<%= link_to 'Back', offerings_path %>
  	</fieldset>
<% end %>

app/views/offerings/show.html.erb
<fieldset>
  <legend>Offerings</legend>
  <p>
    <label for="Offering">Offering</label>
    <%= @offering.offering %>
  </p>
</fieldset>

<fieldset>
	<%= link_to 'Edit', edit_offering_path(@offering) %> |
	<%= link_to 'Back', offerings_path %>
</fieldset>