config/routes.rb
Findagrapher::Application.routes.draw do
  resources :shoots

  resources :services

  resources :offerings

  resources :photographers, :login

  match 'photographers/:id/photos' => 'photographers#photos', :as => :photographers_photos
  match 'photographers/get_flickr_photo/:fid' => 'photographers#get_flickr_photo', :as => :get_flickr_photo

  root :to => 'home#index'

end

app/models/photographer.rb
class Photographer < ActiveRecord::Base
  attr_accessible :name, :photo, :portfolio, :place, :email, :event_list, :offering_list, :service_list

  validates :name, :presence => true
  validates :place, :presence => true
  validates :email, :presence => true

  has_and_belongs_to_many :event_types
  has_and_belongs_to_many :offerings
  has_and_belongs_to_many :services

  attr_accessor :event_list
  attr_accessor :offering_list
  attr_accessor :service_list
  
  after_save :update_event_types
  after_save :update_offering_list
  after_save :update_service_list

  
  
  private

  def update_event_types
  	event_types.delete_all
  	selected_events = event_list.nil? ? [] : event_list.keys.collect{ |id| EventType.find_by_id(id)}
  	selected_events.each { |event| self.event_types << event}
  end
  
  def update_offering_list
  	offerings.delete_all
  	selected_offerings = offering_list.nil? ? [] : offering_list.keys.collect{ |id| Offering.find_by_id(id)}
  	selected_offerings.each { |offering| self.offerings << offering}
  end
  
  def update_service_list
  	services.delete_all
  	selected_services = service_list.nil? ? [] : service_list.keys.collect{ |id| Service.find_by_id(id)}
  	selected_services.each { |service| self.services << service}
  end
end

app/controllers/photographers_controller.rb
class PhotographersController < ApplicationController
  before_filter :authorize, :only => [:index, :show, :edit, :photos]

  # GET /photographers
  # GET /photographers.json
  def index
    @photographers = Photographer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photographers }
    end
  end

  # GET /photographers/1
  # GET /photographers/1.json
  def show
    @photographer = Photographer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photographer }
    end
  end

  # GET /photographers/new
  # GET /photographers/new.json
  def new
    @photographer = Photographer.new
    get_all_events
    get_all_offerings
    get_all_services

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photographer }
    end
  end

  # GET /photographers/1/edit
  def edit
    @photographer = Photographer.find(params[:id])
  end

  # POST /photographers
  # POST /photographers.json
  def create
    @photographer = Photographer.new(params[:photographer])
    get_all_events
    get_all_offerings
    get_all_services

    respond_to do |format|
      if @photographer.save
        format.html { redirect_to @photographer, notice: 'Photographer was successfully created.' }
        format.json { render json: @photographer, status: :created, location: @photographer }
      else
        format.html { render action: "new" }
        format.json { render json: @photographer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photographers/1
  # PUT /photographers/1.json
  def update
    params[:events] ||= {}
    @photographer = Photographer.find(params[:id])
    get_all_events
    get_all_offerings
    get_all_services

    respond_to do |format|
      if @photographer.update_attributes(params[:photographer])
        format.html { redirect_to @photographer, notice: 'Photographer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photographer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photographers/1
  # DELETE /photographers/1.json
  def destroy
    @photographer = Photographer.find(params[:id])
    @photographer.destroy

    respond_to do |format|
      format.html { redirect_to photographers_url }
      format.json { head :no_content }
    end
  end

  def photos
    @photographer = Photographer.find(params[:id])
    @pictures = []
    from = (params[:from] || 1).to_f
    to = (params[:to] || 15).to_f

    portfolio = @photographer.portfolio

    if (portfolio.split("facebook.com/").length > 1)
      @pictures = pictures = get_photos_from_facebook(portfolio)
      @pictures = @pictures[from..to]
    elsif (portfolio.split("flickr.com/").length > 1)
      @pictures = get_photos_from_flickr(portfolio)
      @pictures = @pictures[from..to]
    else
      @pictures = []
    end

    render :layout => false
  end

  def get_flickr_photo
    flickr = FlickRaw::Flickr.new
    info = flickr.photos.getInfo(:photo_id => params[:fid])
    redirect_to FlickRaw.url_b(info)
  end

  def get_photos_from_facebook(url)
    pictures = []
    @app = @graph.get_object(APP_CONFIG[:facebook][:app_id])
    username = url.split("facebook.com/")[1]
    fql_query = "SELECT page_id, pic FROM page WHERE username = '#{username}'"
    page = @graph.fql_query(fql_query)
    page_id = page.first["page_id"]
    pictures = @graph.fql_query("SELECT src, src_height, src_width, src_small, src_small_height, src_small_width FROM photo WHERE pid IN (SELECT pid FROM photo WHERE aid IN (SELECT aid FROM album WHERE owner='#{page_id}' AND type!='profile'))")
    return pictures
  end

  def get_photos_from_flickr(url)
    pictures = []
    FlickRaw.api_key = APP_CONFIG[:flickr][:key]
    FlickRaw.shared_secret = APP_CONFIG[:flickr][:secret]

    flickr = FlickRaw::Flickr.new
    photos = flickr.photos.search(:user_id => '48898139@N00')
    photos.each do |p|
      pictures.push({ "src" => "/photographers/get_flickr_photo/#{p["id"]}" })
    end
    return pictures
  end

  def get_all_offerings
    @offerings = Offering.find(:all)
  end

  def get_all_events
    @events = EventType.find(:all)
  end
  
  def get_all_services
    @services = Service.find(:all)
  end
end

app/helpers/photographers_helper.rb
module PhotographersHelper
end

app/views/photographers/_form.html.erb
<div class="form">
  <%= form_for(@photographer) do |f| %>
    <% if @photographer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@photographer.errors.count, "error") %> prohibited this photographer from being saved:</h2>

        <ul>
        <% @photographer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <h3 class="span8 offset4">Tell us what you're looking for.</h3>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        I'm interested in shooting:
      </div>
      <div class="f-content span8">
        <% @events.each_with_index do |event| %>
          <div class="option">
            <%= check_box_tag( "photographer[event_list][#{event.id}]", 
                                "1", 
                                @photographer.event_types.detect{|d| d == event}) %>
            <%= "#{event.event}"%>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        I'm willing to offer:
      </div>
      <div class="f-content span8">
        <% @offerings.each_with_index do |o| %>
          <div class="option">
            <%= check_box_tag( "photographer[offering_list][#{o.id}]", 
                                        "1", 
                                        @photographer.offerings.detect{|d| d == o}) %>
            <%= "#{o.offering}"%>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        After the shoot, I can provide:
      </div>
      <div class="f-content span8">
        <% @services.each_with_index do |s| %>
          <div class="option">
            <%= check_box_tag( "photographer[service_list][#{s.id}]", 
                                        "1", 
                                        @photographer.services.detect{|d| d == s}) %>
            <%= "#{s.service}"%>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row">
      <h3 class="span8 offset4">A bit about yourself.</h3>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        Your full name:
      </div>
      <div class="f-content span8">
        <%= f.text_field :name %>
      </div>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        Your location:
      </div>
      <div class="f-content span8">
        <%= f.text_field :place %>
      </div>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        Link to your portfolio:
      </div>
      <div class="f-content span8">
        http://<%= f.text_field :portfolio %>
        <br/>
        <div class="note">
          Your facebook page, flickr page or your own website.
        </div>
      </div>
    </div>

    <div class="row">
      <h3 class="span8 offset4">How would you like to be notified?</h3>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        E-Mail:
      </div>
      <div class="f-content span8">
        <%= f.text_field :email %>
        <br/>
        <div class="note">
          <h4>We won't spam you.</h4>
          <div>
            Remember, you can always instantaly turn off this notification once you find your photographer.
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="f-name span4">
        Notify:
      </div>
      <div class="f-content span8">
        <%
          types = ['Once a day', 'Twice a week', 'Once a week']
          types.each_with_index do |o|
        %>
          <div class="option">
            <input type="checkbox" />
            <%= o %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="f-content span8 offset4">
        <%= f.submit "Register", :class => "btn btn-success" %>
      </div>
    </div>

  <% end %>
</div>

app/views/photographers/edit.html.erb
<h1>Editing photographer</h1>

<%= render 'form' %>

<%= link_to 'Show', @photographer %> |
<%= link_to 'Back', photographers_path %>

app/views/photographers/index.html.erb
<h1>Listing photographers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Photo</th>
    <th>Portfolio</th>
    <th>Email</th>
    <th>Place</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photographers.each do |photographer| %>
  <tr>
    <td><%= photographer.name %></td>
    <td><%= photographer.photo %></td>
    <td><%= photographer.portfolio %></td>
    <td><%= photographer.email %></td>
    <td><%= photographer.place %></td>
    <td><%= link_to 'Show', photographer %></td>
    <td><%= link_to 'Edit', edit_photographer_path(photographer) %></td>
    <td><%= link_to 'Destroy', photographer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photographer', new_photographer_path %>

app/views/photographers/new.html.erb
<div class="container">
	<div class="row">
		<div class="span12">
			<div class="white-box pad-top">
				<div class="title">
					<h2>Register</h2>
				</div>
				<div class="content">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/photographers/photos.html.erb
<% @pictures.each_with_index do |p| %>
	<%= image_tag p['src'] %>
<% end %>

app/views/photographers/show.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="white-box pad-top" id="profile">
        <div class="title">
          <h2> <%= @photographer.name %></h2>
        </div>
        <div class="content clearfix">
          <div class="profile-pic">
            <%= image_tag "/assets/default-profile-pic.jpg" %>
          </div>
          <div class="profile-info">
            <div class="form">
              
              <div class="row">
                <div class="f-name span2">Shoots:</div>
                <div class="f-content span6">
                  <% @photographer.event_types.each_with_index do |e|  %>
                  <%= "#{e.event}, " %>
                  <% end %>
                </div>
              </div>

              <div class="row">
                <div class="f-name span2">Offers:</div>
                <div class="f-content span6">
                  <% @photographer.offerings.each_with_index do |o|  %>
                  <%= "#{o.offering}, " %>
                  <% end %>
                </div>
              </div>

              <div class="row">
                <div class="f-name span2">Provides:</div>
                <div class="f-content span6">
                  <% @photographer.services.each_with_index do |s|  %>
                  <%= "#{s.service}, " %>
                  <% end %>
                </div>
              </div>

              <div class="row">
                <div class="f-name span2">Location:</div>
                <div class="f-content span6"><%= @photographer.place %></div>
              </div>

              <div class="row">
                <div class="f-name span2">Contact:</div>
                <div class="f-content span6"><%= @photographer.email %></div>
              </div>

              <div class="row">
                <div class="f-name span2">Portfolio:</div>
                <div class="f-content span6">
                  <strong>
                    <a href=<%= @photographer.portfolio %> target="_blank"><%= @photographer.portfolio %></a> <i class="icon-share-alt"></i>
                  </strong>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <div class="black-box pad-top">
        <div class="title">
          <h2>Recent shots</h2>
        </div>
        <div class="content" id="portfolio-pictures">
          <div class="pictures">
            Loading pictures from portfolio...
          </div>
          <div class="load clearfix">
            <a href="javascript: void(0);" class="btn load-more hide">Load more</a>
          </div>
        </div>
    </div>
  </div>
</div>

<script>

  $(function(){

    var loadMore = $('#portfolio-pictures .load-more'),
        pictureContainer = $('#portfolio-pictures .pictures'),
        pageSize = 15;

    pictureContainer.masonry({
      itemSelector: 'img'
    });

    loadMore.click(function(){
      var from = pictureContainer.find('img').length,
          to = from + pageSize - 1;

      loadMore.hide();
      $.ajax({
        url: '<%= photographers_photos_path(@photographer) %>',
        data: {
          from: from,
          to: to
        },
        success: function(r){
          var el = pictureContainer;
          var imagesPresent = el.find('img').length;
          if(imagesPresent){
            el.append(r);
          } else {
            el.html(r);
          }
          el.find('img').each(function(){
            $(this).load(function(){
              var el = $(this);
              setTimeout(function(){
                pictureContainer.masonry('reload');
              }, 10);
            });
          });
        },
        complete: function(){
          loadMore.show();
        }
      });
    }).click();

  })

</script>